name: Morpho CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: |
        sudo apt update
        sudo apt install libglfw3
        sudo apt install libsuitesparse-dev
        sudo apt install liblapacke-dev
        python -m pip install --upgrade pip
        python -m pip install regex colored
    - name: make 
      run: (cd morpho5; sudo make -f Makefile.linux install)
    - name: test
      run: (cd test; python3 test.py -c)
    
    - name: configureMorphoView
      run: |
        sudo apt install povray
        sudo apt install libglfw3 libglfw3-dev
    - name: makeMorphoview
      run: (cd morphoview; sudo make -f Makefile.linux install)
    - name: testExamples
      run: (cd examples; python3 examples.py -c)

    - name: makeNoNanBoxing
      run: (cd morpho5; sudo make -f Makefile.linux nonanboxing)
    - name: testNoNanBoxing
      run: (cd test; python3 test.py -c)

    - name: makeGarbageCollectorTest
      run: (cd morpho5; sudo make -f Makefile.linux garbagecollectortest)
    - name: testGarbageCollectorTest
      run: (cd test; python3 test.py -c)
